spring.application.name=hr-worker
server.port=${PORT:0}

eureka.instance.instance-id=${spring.application.name}:${spring.application.instance_id:${random.value}}

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# 🔥 MUITO IMPORTANTE
spring.jpa.defer-datasource-initialization=true


# Eureka Client
eureka.client.service-url.defaultZone=http://hr-eureka-server:8761/eureka
